### ISSUE TITLE
Similarity search with set-sketch-paper

### ISSUE THREAD

**Issue by lutfia95** [dynatrace-research/set-sketch-paper#1]
Hi, 

I was using HLL --cmp for some similarity searches between two data sets (Sequencing data vs. Reference Genome). I would like to try the same with set-sketch. Is there anyway to run a similarity search using set-sketch? 

Thanks

best, 
Ahmad

**Comment by oertl** [comment]
Could you please give some more details what you mean with "HLL --cmp"? I guess you refer to some HyperLogLog implementation. In general, SetSketch is better suited for similarity search than HyperLogLog.

**Comment by lutfia95** [comment]
I want to use SetSketch for similarity search, can you please explain to me, how can I use SetSketch?

**Comment by oertl** [comment]
It would be very helpful if you could provide some more context. This repository only contains a prototype implementation of SetSketch and corresponding algorithms for set similarity estimation. Even though SetSketch can be used as a building block, it is not a ready-to-use library for similarity search. Therefore, if you don't mind, I'll close this topic. However, feel free to send me a mail describing the problem in more detail.

**Comment by lutfia95** [comment]
Thanks for the answer!
I wanted to try set-sketch with a similarity search (matching k-mers between two data sets) but if it isn't a ready to use library for similarity search, I will only finish reading the paper, which is really interesting for me. 

Best,
Ahmad
